---
####################################################
#          ModuleBuilder Configuration             #
####################################################

CopyPaths:
  - en-US
  - Modules
# '.psm1' Prefix and Suffixes
Prefix: prefix.ps1
#Suffix: suffix.ps1
Encoding: UTF8
VersionedOutputDirectory: true
BuiltModuleSubdirectory: builtModule

ModuleBuildTasks:
  Sampler:
    - '*.build.Sampler.ib.tasks'
  Sampler.GitHubTasks:
    - '*.ib.tasks'
  DscResource.DocGenerator:
    - 'Task.*'
  DscResource.Test:
    - 'Task.*'

TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

####################################################
#     Dependent Modules Configuration (Sampler)    #
####################################################

NestedModule:
  DscResource.Common:
    CopyOnly: true
    Path: ./output/RequiredModules/DscResource.Common
    AddToManifest: false
    Exclude: PSGetModuleInfo.xml

####################################################
#            Pipeline Configuration                #
####################################################

BuildWorkflow:
  '.':
    - build
    - test

  build:
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Create_changelog_release_output

  docs:
    - Generate_Conceptual_Help
    - Generate_Wiki_Content
    - Generate_Wiki_Sidebar
    - Clean_Markdown_Metadata
    - Package_Wiki_Content

  pack:
    - build
    - docs
    - package_module_nupkg

  hqrmtest:
    - DscResource_Tests_Stop_On_Fail
    #- Invoke_HQRM_Tests_Stop_On_Fail #Pester 5

  test:
    - Pester_Tests_Stop_On_Fail
    - Convert_Pester_Coverage
    - Pester_if_Code_Coverage_Under_Threshold

  merge:
    - Merge_CodeCoverage_Files

  publish:
    - Publish_release_to_GitHub
    - publish_module_to_gallery
    - Publish_GitHub_Wiki_Content

####################################################
#       PESTER  Configuration                      #
####################################################

Pester:
  OutputFormat: NUnitXML
  ExcludeFromCodeCoverage:
    - Modules/DscResource.Common
  Script:
    # Only run on unit test on './build.ps1 -Task test'
    - tests/Unit
  ExcludeTag:
  Tag:
  CodeCoverageThreshold: 40
  CodeCoverageOutputFile: CodeCoverage.JaCoCo.xml
  CodeCoverageOutputFileEncoding: ascii

####################################################
#           Code Coverage Configuration            #
####################################################

CodeCoverage:
  # Filename of the file that will be outputted by the task Merge_CodeCoverage_Files.
  CodeCoverageMergedOutputFile: JaCoCo_coverage.xml
  # File pattern used to search for files under the ./output/testResults folder
  # by task Merge_CodeCoverage_Files.
  CodeCoverageFilePattern: Codecov*.xml

####################################################
#      Pester Configuration (DscResource.Test)     #
####################################################

DscTest:
  ExcludeTag:
    - 'Common Tests - New Error-Level Script Analyzer Rules'
    - 'Common Tests - PS Script Analyzer on Resource Files' #Temp to pass build and resource is fixed
  Tag:
  ExcludeSourceFile:
    - output
  ExcludeModuleFile:
    - Modules/DscResource.Common
  MainGitBranch: main

####################################################
#               GitHub Configuration               #
####################################################

GitHubConfig:
  GitHubFilesToAdd:
    - 'CHANGELOG.md'
  GitHubConfigUserName: dscbot
  GitHubConfigUserEmail: dsccommunity@outlook.com
  UpdateChangelogOnPrerelease: false

####################################################
#      DscResource.DocGenerator Configuration      #
####################################################

DscResource.DocGenerator:
  Generate_Conceptual_Help:
    MarkdownCodeRegularExpression:
      - '\`(.+?)\`' # Match inline code-block
      - '\\(\\)' # Match escaped backslash
      - '\[[^\[]+\]\((.+?)\)' # Match markdown URL
      - '_(.+?)_' # Match Italic (underscore)
      - '\*\*(.+?)\*\*' # Match bold
      - '\*(.+?)\*' # Match Italic (asterisk)
  Generate_Markdown_For_DSC_Resources:
    MofResourceMetadata:
      Type: MofResource
      Category: Resources
    ClassResourceMetadata:
      Type: ClassResource
      Category: Resources
    CompositeResourceMetadata:
      Type: CompositeResource
      Category: Resources
  Generate_Wiki_Sidebar:
    AlwaysOverwrite: true
