Enum DescriptorType {

    Analytics
    AnalyticsViews
    ReleaseManagement
    AuditLog
    Identity
    WorkItemTrackingAdministration
    DistributedTask
    GitRepositories
    VersionControlItems2
    EventSubscriber
    WorkItemTrackingProvision
    ServiceEndpoints
    ServiceHooks
    Collection
    Proxy
    Plan
    Process
    AccountAdminSecurity
    Library
    Environment
    Project
    EventSubscription
    ProjectAnalysisLanguageMetrics
    Tagging
    MetaTask
    Iteration
    WorkItemQueryFolders
    Favorites
    Registry
    Graph
    ViewActivityPaneSecurity
    Job
    EventPublish
    WorkItemTracking
    StrongBox
    Server
    TestManagement
    SettingEntries
    BuildAdministration
    Location
    Boards
    OrganizationLevelData
    UtilizationPermissions
    WorkItemsHub
    WebPlatform
    VersionControlPrivileges
    Workspaces
    CrossProjectWidgetView
    WorkItemTrackingConfiguration
    DiscussionThreads
    BoardsExternalIntegration
    DataProvider
    Social
    Security
    IdentityPicker
    ServicingOrchestration
    Build
    DashboardsPrivileges
    CSS
    VersionControlItems

}
